Preserve page description metadata
dita-ot/org.dita-ot.html pull request #10
Opened 2020-08-26 21:41 UTC by infotexture

Our site plugin is currently designed in a way that does not preserve metadata from individual pages, as a common layout template is used for all pages, so the metadata propagated to the `<head>` element in default HTML5 output is lost when generating site output.

Currently, page titles are preserved with the code on [dita2html.xsl#L29-L30](https://github.com/dita-ot/org.dita-ot.html/blob/feature/no-commit-meta/xsl/dita2html.xsl#L29-L30).

For SEO purposes, we should at least preserve the `<shortdesc>` information in `<meta name="description" content="…"/>`

2020-09-04 21:11 UTC, infotexture commented
@jelovirt The description is preserved with these changes, but I'm not sure if we should propagate other metadata while we're at it, or add the original source file name to the YAML header for https://github.com/dita-ot/website/issues/134.

Any thoughts or preferences?

2020-09-05 22:21 UTC, infotexture commented on xsl/dita2html.xsl
> +    <xsl:apply-templates select="*[contains(@class, ' topic/shortdesc ')]" mode="text-only"/>
Noticed this syntax only catches cases where `<shortdesc>` appears by itself, but not within `<abstract>`.

Not sure how to handle both.

2020-10-29 07:38 UTC, jelovirt requested changes

2020-10-29 07:38 UTC, jelovirt commented on xsl/dita2html.xsl
> +    <xsl:text>'&#xA;</xsl:text>
```suggestion
    <xsl:if test="*[contains(@class, ' topic/shortdesc ')]">
      <xsl:text>description: '</xsl:text>
      <xsl:apply-templates select="*[contains(@class, ' topic/shortdesc ')]" mode="text-only"/>
      <xsl:text>'&#xA;</xsl:text>
    </xsl:if>
```

2020-11-05 19:06 UTC, jelovirt approved these changes

2020-11-05 19:06 UTC, jelovirt commented on xsl/dita2html.xsl
> +    </xsl:if>
Shouldn't this do the trick?

```suggestion
    <xsl:variable name="shortdescs" as="element()*"
                  select="*[contains(@class, ' topic/shortdesc ')] |
                          *[contains(@class, ' topic/abstract ')]/*[contains(@class, ' topic/shortdesc ')]"/>
    <xsl:if test="exists($shortdescs)">
      <xsl:text>description: '</xsl:text>
      <xsl:for-each select="$shortdescs">
        <xsl:if test="position() ne 1">
          <xsl:text> </text>
        </xsl:if>
        <xsl:apply-templates select=". mode="text-only"/>
      </xsl:for-each>
      <xsl:text>'&#xA;</xsl:text>
    </xsl:if>
```

2020-11-05 20:45 UTC, infotexture commented
@jelovirt Thanks. 

There were a few minor syntax errors in the suggestion, but they were easily fixed in e1f50b6, and short descriptions in abstracts are now included as expected.

2020-11-05 20:47 UTC, merged